### ISSUE TITLE
Are there queuing modes in Processing stations?

### ISSUE THREAD

**Issue by kapil-dhaimade** [A-Herzog/Warteschlangensimulator#11]
Hi,
I'm using this simulator since few days. It is amazing, just what I needed.

I can see examples of queuing disciplines like FIFO, LIFO queues on the Example page. But I can't find a way to set the queuing mode (FIFO, LIFO, etc.) of a Processing station in the software. No mention of the same in Help too. 

Please guide me about the same. Thanks.

**Comment by A-Herzog** [comment]
Warteschlangensimulator is not using a hard coded queueing discipline model. Each customer in a queue has a priority. The customer with the highest priority is chosen for service. The priority is defined via a formula. The current waiting time of the current client is denoted by the variable "w" in this formula. So using "w" means FIFO, "-w" is LIFO and "random()" means service in random order. By using "w" for one customer type and "w+50" for example for another type, different priorities between different customer types can be defined.

The different queueing disciplines are defined exactly this way in the example model you are referring to.

So this is not an issue in the program.
