### ISSUE TITLE
Can't add variable to source or edit it in clients

### ISSUE THREAD

**Issue by srvaroa** [A-Herzog/Warteschlangensimulator#14]
Hi, and thanks for publishing the simulator.

I'm trying to configure a source so that each generated client gets a variable, but I can't get the dialog to accept any value.

I've tried a variable name (e.g. "nr") as well as ClientData(nr) as suggested in the help, but neither work. I don't have a global variable "nr" defined so I don't think this is due to a conflict). 

What is the right way of defining a variable to assign in each client?

![image](https://github.com/A-Herzog/Warteschlangensimulator/assets/346110/c56f760a-c7ec-4347-9c6c-01dd4805ae2d)

I have tried adding a Variable element and initialize it there, but I can't get it to work either. I am assuming that this is how I should write to the client's variable:

![image](https://github.com/A-Herzog/Warteschlangensimulator/assets/346110/ffe66d3c-2a02-4fe5-8527-c598f66f2a51)

Thanks!

**Comment by A-Herzog** [comment]
By "ClientData" you can access an open vector associated with each client object (individual values for each client object - exactly what you want to have). You can write any number to any non-negative index and use these values later at other stations. The index itself on the left side of the assignment statement has to be a plain number (not an expression or a variable). So you cannot assign values to "clientdata(nr)" (with "nr" a global variable). Only left sides like "clientdata(0)", "clientdata(1)" etc. are valid. [The "nr" on the help page is only a placeholder for a number.]

If you want to calculate the index first before using it in a value assignment, you have to use a script station. For example in Javascript mode you can write "Simulation.setClientValue(index,value);" with any expression that calculates to a non-negative integer for "index" and any numerical value for "value".
